In [32]:
import numpy as np
import pandas as pd

In [33]:
df = pd.read_csv('sales.csv')
df

    Order_ID     Product     Category  Revenue  Quantity Region  Order_Date
0       1001      Laptop  Electronics  55000.0         1  North  2026-10-01
1       1002       Mouse  Accessories    750.0         3  South  2026-10-02
2       1003    Keyboard  Accessories   1800.0         2   East  2026-10-02
3       1004     Monitor  Electronics  12000.0         1   West  2026-10-03
4       1005      Laptop  Electronics  52000.0         1    NaN  2026-10-04
5       1006       Mouse  Accessories    750.0         2  North  2026-10-05
6       1007  Headphones  Accessories   2500.0         2  South  2026-10-05
7       1008    Keyboard  Accessories      NaN         1   West  2026-10-06
8       1009     Monitor  Electronics  11500.0         1  North  2026-10-07
9       1010      Laptop  Electronics  56000.0         1  South  2026-10-08
10      1011       Mouse  Accessories    800.0         4   East  2026-10-09
11      1012  Headphones  Accessories   2400.0         2   West  2026-10-10
12      1002       Mouse  Accessories    750.0         3  South  2026-10-02

In [6]:
df.shape

(13, 7)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    13 non-null     int64
 1   Product     13 non-null     str
 2   Category    13 non-null     str
 3   Revenue     12 non-null     float64
 4   Quantity    13 non-null     int64
 5   Region      12 non-null     str
 6   Order_Date  13 non-null     str
dtypes: float64(1), int64(2), str(4)
memory usage: 1.2 KB

In [19]:
df.groupby('Category')['Revenue'].sum()

Category
Accessories      9750.0
Electronics    186500.0
Name: Revenue, dtype: float64

In [21]:
df.isna().any

<bound method DataFrame.any of     Order_ID  Product  Category  Revenue  Quantity  Region  Order_Date
0      False    False     False    False     False   False       False
1      False    False     False    False     False   False       False
2      False    False     False    False     False   False       False
3      False    False     False    False     False   False       False
4      False    False     False    False     False    True       False
5      False    False     False    False     False   False       False
6      False    False     False    False     False   False       False
7      False    False     False     True     False   False       False
8      False    False     False    False     False   False       False
9      False    False     False    False     False   False       False
10     False    False     False    False     False   False       False
11     False    False     False    False     False   False       False
12     False    False     False    False     False   False       False>

In [40]:
df['Revenue']=df['Revenue'].fillna(df['Revenue'].mean())
df

    Order_ID     Product     Category  Revenue  Quantity Region  Order_Date
0       1001      Laptop  Electronics  55000.0         1  North  2026-10-01
1       1002       Mouse  Accessories    750.0         3  South  2026-10-02
2       1003    Keyboard  Accessories   1800.0         2   East  2026-10-02
3       1004     Monitor  Electronics  12000.0         1   West  2026-10-03
5       1006       Mouse  Accessories    750.0         2  North  2026-10-05
6       1007  Headphones  Accessories   2500.0         2  South  2026-10-05
8       1009     Monitor  Electronics  11500.0         1  North  2026-10-07
9       1010      Laptop  Electronics  56000.0         1  South  2026-10-08
10      1011       Mouse  Accessories    800.0         4   East  2026-10-09
11      1012  Headphones  Accessories   2400.0         2   West  2026-10-10
12      1002       Mouse  Accessories    750.0         3  South  2026-10-02

In [37]:
df_comp = df.dropna()
df_comp

    Order_ID     Product     Category  Revenue  Quantity Region  Order_Date
0       1001      Laptop  Electronics  55000.0         1  North  2026-10-01
1       1002       Mouse  Accessories    750.0         3  South  2026-10-02
2       1003    Keyboard  Accessories   1800.0         2   East  2026-10-02
3       1004     Monitor  Electronics  12000.0         1   West  2026-10-03
5       1006       Mouse  Accessories    750.0         2  North  2026-10-05
6       1007  Headphones  Accessories   2500.0         2  South  2026-10-05
8       1009     Monitor  Electronics  11500.0         1  North  2026-10-07
9       1010      Laptop  Electronics  56000.0         1  South  2026-10-08
10      1011       Mouse  Accessories    800.0         4   East  2026-10-09
11      1012  Headphones  Accessories   2400.0         2   West  2026-10-10
12      1002       Mouse  Accessories    750.0         3  South  2026-10-02

In [38]:
df.sort_values(by=['Revenue','Quantity'], ascending=[False, False])

    Order_ID     Product     Category  Revenue  Quantity Region  Order_Date
9       1010      Laptop  Electronics  56000.0         1  South  2026-10-08
0       1001      Laptop  Electronics  55000.0         1  North  2026-10-01
3       1004     Monitor  Electronics  12000.0         1   West  2026-10-03
8       1009     Monitor  Electronics  11500.0         1  North  2026-10-07
6       1007  Headphones  Accessories   2500.0         2  South  2026-10-05
11      1012  Headphones  Accessories   2400.0         2   West  2026-10-10
2       1003    Keyboard  Accessories   1800.0         2   East  2026-10-02
10      1011       Mouse  Accessories    800.0         4   East  2026-10-09
1       1002       Mouse  Accessories    750.0         3  South  2026-10-02
12      1002       Mouse  Accessories    750.0         3  South  2026-10-02
5       1006       Mouse  Accessories    750.0         2  North  2026-10-05

In [ ]:
df.fillna()['Revenue'].mean()

In [41]:
num_df = df.select_dtypes(include='number')
num_df

    Order_ID  Revenue  Quantity
0       1001  55000.0         1
1       1002    750.0         3
2       1003   1800.0         2
3       1004  12000.0         1
5       1006    750.0         2
6       1007   2500.0         2
8       1009  11500.0         1
9       1010  56000.0         1
10      1011    800.0         4
11      1012   2400.0         2
12      1002    750.0         3

In [43]:
cor_matrix = num_df.corr()
print(cor_matrix)

          Order_ID   Revenue  Quantity
Order_ID  1.000000 -0.052133  0.050490
Revenue  -0.052133  1.000000 -0.615122
Quantity  0.050490 -0.615122  1.000000